--make the blogful users table
CREATE TABLE blogful_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  fullname TEXT NOT NULL,
  username TEXT NOT NULL UNIQUE,
  password TEXT,
  nickname TEXT,
  date_created TIMESTAMPTZ NOT NULL DEFAULT now()
);

--ARTICLES TABLE MUST BE ALTERED TO ADD THE FOREIGN KEY COLUMN
ALTER TABLE blogful_articles
  ADD COLUMN
    author INTEGER REFERENCES blogful_users(id)
    ON DELETE SET NULL;